spring:
  datasource:
     driverClassName: org.h2.Driver
     url: "jdbc:h2:mem:tbdb"
     username: root
     password:
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate.dialect: org.hibernate.dialect.H2Dialect
     hibernate.ddl-auto: create
     hibernate.hbm2ddl.auto: create
     generate-ddl: true
     show-sql: true
server:
  port: 9090